"""empty message

Revision ID: 7b2b91872245
Revises: ea67a3db0d21
Create Date: 2019-08-08 15:14:12.233755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b2b91872245'
down_revision = 'ea67a3db0d21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('shelter', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'shelter')
    # ### end Alembic commands ###
